// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutripuc_E3.Models;

#nullable disable

namespace Nutripuc_E3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nutripuc_E3.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlimentacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AtividadeFisicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDoRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDoUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlimentacaoId");

                    b.HasIndex("AtividadeFisicaId");

                    b.HasIndex("IdDoUsuario");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Nutripuc_E3.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Nutripuc_E3.Models.Alimentacao", b =>
                {
                    b.HasBaseType("Nutripuc_E3.Models.Registro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RefeicaoDoLixo")
                        .HasColumnType("bit");

                    b.Property<int>("TipoDeRefeicao")
                        .HasColumnType("int");

                    b.ToTable("Alimentacao", (string)null);
                });

            modelBuilder.Entity("Nutripuc_E3.Models.AtividadeFisica", b =>
                {
                    b.HasBaseType("Nutripuc_E3.Models.Registro");

                    b.Property<string>("CategoriaDaAtividade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Intensidade")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TituloDoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AtividadeFisica", (string)null);
                });

            modelBuilder.Entity("Nutripuc_E3.Models.Registro", b =>
                {
                    b.HasOne("Nutripuc_E3.Models.Alimentacao", "Alimentacao")
                        .WithMany()
                        .HasForeignKey("AlimentacaoId");

                    b.HasOne("Nutripuc_E3.Models.AtividadeFisica", "AtividadeFisica")
                        .WithMany()
                        .HasForeignKey("AtividadeFisicaId");

                    b.HasOne("Nutripuc_E3.Models.Usuario", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("IdDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimentacao");

                    b.Navigation("AtividadeFisica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Nutripuc_E3.Models.Alimentacao", b =>
                {
                    b.HasOne("Nutripuc_E3.Models.Registro", null)
                        .WithOne()
                        .HasForeignKey("Nutripuc_E3.Models.Alimentacao", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutripuc_E3.Models.AtividadeFisica", b =>
                {
                    b.HasOne("Nutripuc_E3.Models.Registro", null)
                        .WithOne()
                        .HasForeignKey("Nutripuc_E3.Models.AtividadeFisica", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nutripuc_E3.Models.Usuario", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
